# Generated by Django 3.1 on 2021-02-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('staff', 'staff'), ('customer', 'customer')], default='customer', max_length=50),
        ),
    ]
