# Generated by Django 3.1 on 2021-02-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_auto_20210225_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_time_list', models.CharField(choices=[('10:00AM - 10:30AM', '10:00AM - 10:30AM'), ('10:30AM - 11:00AM', '10:30AM - 11:00AM'), ('11:30AM - 12:00PM', '11:30AM - 12:00PM'), ('12:00PM - 12:30PM', '12:00PM - 12:30PM'), ('2:30PM - 3:00PM', '2:30PM - 3:00PM'), ('3:00PM - 3:30PM', '3:00PM - 3:30AM'), ('4:00PM - 4:30PM', '4:00PM - 4:30PM'), ('4:30PM - 5:00PM', '4:30PM - 5:00PM')], max_length=100)),
            ],
        ),
    ]
