# Generated by Django 3.1 on 2021-02-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0008_appointment_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient_email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_mobile',
            field=models.CharField(max_length=10),
        ),
    ]
